### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by max5962** [swingerman/lovelace-fluid-level-background-card#114]
Hello,

i'm using V1 and it seems a little buggy. 

![image](https://user-images.githubusercontent.com/34659571/170268918-dc2abad8-68bc-4243-a575-59e32a8d9a43.png)

`
            - type: custom:fluid-level-background-card
               entity: sensor.pixel_6_pro_battery_level
               level_color:
                    - 20
                    - 40
                    - 65
               card:
                   type: 'custom:button-card'
                   template: card_person
                   variables:
                     ulm_card_person_entity: person.maxime
                     ulm_card_person_use_entity_picture: true
                     ulm_card_person_zone1: zone.travail_max
                     ulm_address: sensor.pixel_6_pro_geocoded_location

`

1. Round corner seems not be fixed
2. The blue round have an icon within ( was working with the V0.3 version ) 
3. Level_color seems not working ( same color for 2 value 10 and 58 ) ( using classical value for level_color ( 20/50/60), the color is black :( ) 

For the blue round it seems that CSS
It seems
![image](https://user-images.githubusercontent.com/34659571/170471130-373241df-02ac-43b4-aa1e-43b190aedd2e.png)

**Comment by max5962** [comment]
This :
https://community.home-assistant.io/t/lovelace-ui-minimalist/322687?u=max5962

**Comment by max5962** [comment]
More precisely this : https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_person/?h=card_person

**Comment by flyrmyr** [comment]
Seems to be the same bug, I'm also seeing the border-radius not matching the corners. I played with some raw
CSS on the inspect panel, but the issue looks to be above the element CardMod can manipulate.
![image](https://user-images.githubusercontent.com/14035884/219566065-11ff63c5-1516-480c-9107-1119a9474b3f.jpeg)

**Comment by ildar170975** [comment]
Described & solved here - https://github.com/swingerman/lovelace-fluid-level-background-card/issues/373

**Comment by swingerman** [comment]
Closing this a duplicate #373
