### ISSUE TITLE
custom title

### ISSUE THREAD

**Issue by hidaba** [swingerman/lovelace-fluid-level-background-card#126]
Hello,
I'm trying  to custom title but not luck with card_mod:
I can't change title format

`square: true
columns: 1
type: custom:fluid-level-background-card
cards:
  - show_name: false
    show_icon: true
    show_state: true
    type: glance
    entities:
      - entity: sensor.acqua_giardino_utilizzo_settimanale
      - entity: sensor.utilizzo_acqua_giardino
    state_color: false
    title: Giardino
card_mod:
  style: |
    ha-card {
      font-size: 9px;
      font-weight: bold;
    }
    .card.title {
      font-size: 20px;
      text-align: center;
      font-weight: bold;
    }
entity: sensor.livello_tanica
card:
  show_name: false
  show_icon: true
  show_state: true
  type: glance
  entities:
    - entity: sensor.acqua_barile_utilizzo_settimanale`

**Comment by ildar170975** [comment]
The posted code is unformatted  & cannot be properly analysed.
It seems to be a wrong mix of the `lovelace-fluid-level-background-card` & a stock `grid` cards.

**Comment by swingerman** [comment]
@hidaba , please post your config in YAML format!
