### ISSUE TITLE
[feat] add color by severity customization

### ISSUE THREAD

**Issue by jybi89** [swingerman/lovelace-fluid-level-background-card#134]
Hi ! thanks for uoy job :)

Can you add  color with the entity value?

exemple with mini graph card :
color_thresholds:
  - color: '#1da4f2'
    value: 5
  - color: '#11f13a'
    value: 28
  - color: '#f0da11'
    value: 31
  - color: '#ef5a0f'
    value: 36
  - color: '#ef1d0f'
    value: 40

thanks

**Comment by azsoccerpop** [comment]
Yes please allow the color to be controlled by thresholds. I would like to use this card with the sensors I have on my pool like pH which has an optimal range. I am using the Gauge card with segment but would love to use this instead:
segments:
      - from: 0
        color: '#db4437'
      - from: 6.8
        color: '#ffa600'
      - from: 7.1
        color: '#43a047'
      - from: 7.7
        color: '#ffa600'
      - from: 8.1
        color: '#db4437'

**Comment by Perfect-Web** [comment]
@swingerman any chance to get this feature implemented ? almost 2 years now :)

**Comment by swingerman** [comment]
> @swingerman any chance to get this feature implemented ? almost 2 years now :)

There is a chance in the coming weeks. I am affected by the war in Ukraine, unfortunately...

**Comment by swingerman** [comment]
Please check [v0.1.6-beta.4](https://github.com/swingerman/lovelace-fluid-level-background-card/releases/tag/v0.1.6-beta.4)

You can set severity this way:

```yaml
severity:
  - value: 20
    color: red
  - value: 50
    color: yellow
  - value: 80
    color: green
```

color can be in almost any format (defined in readme)

**Comment by SabatoArdolino** [comment]
Hi is it a way to include range ?
From 0 to 20 color Red
from 20 to 70 yellow
grater than 70 green 
??

**Comment by swingerman** [comment]
Yes. Each severity step defines a color above it's value. The color changes if there is severity set with a higher value. 
See above.
