### ISSUE TITLE
[FEAT] Ability To Change Background Color

### ISSUE THREAD

**Issue by swingerman** [swingerman/lovelace-fluid-level-background-card#17]

**Comment by aaamoeder** [comment]
I've changed the hardcoded values on line 208 in the .js but the color on the frontend does not seem to adapt the changes ?
Is there anywhere else I should be looking ? (untill you manage to find the time to add the option ofcourse :) )

**Comment by swingerman** [comment]
> I've changed the hardcoded values on line 208 in the .js but the color on the frontend does not seem to adapt the changes ? Is there anywhere else I should be looking ? (untill you manage to find the time to add the option ofcourse :) )

I will do the color choser soon, but until then you can set a hardcoded color here: https://github.com/swingerman/lovelace-fluid-level-background-card/blob/c96e60f6b017b2abbb89387fa9e792a0401be29f/src/fluid-background.ts#L48

`this.setBackgroundcolor('your color');`

**Comment by aaamoeder** [comment]
thanks for your quick reply !!

Not sure which lines you're referring to though ..?

My .js file is only 250 lines long and has no mention of those vars 😕 

sorry for bothering you about this, but the level of our well being green and not blue just tickles my funny bone ... 😛

**Comment by aaamoeder** [comment]
thanks a million !!!! 🙇‍♂️ 🙇‍♂️ 🙇‍♂️ 🙇‍♂️ 🙇‍♂️ 🙇‍♂️

**Comment by djdfynec** [comment]
> > I've changed the hardcoded values on line 208 in the .js but the color on the frontend does not seem to adapt the changes ? Is there anywhere else I should be looking ? (untill you manage to find the time to add the option ofcourse :) )
> 
> I will do the color chooser soon, but until then, you can set a hardcoded color here:
> 
> Background color: Change it in line 930 Liquid foreground-color: line 983 Liquid background-color: line 990

Tell me, when will the ability to change the background be implemented?

**Comment by swingerman** [comment]
I will have some time in the next two weeks

**Comment by djdfynec** [comment]
> I will have some time in the next two weeks

it would be just amazing 

I have a buffer tank and need to implement visualization with a layer of water, but without a background this is impossible

**Comment by djdfynec** [comment]
Good afternoon, is there any progress on our issue?

**Comment by djdfynec** [comment]
> I will have some time in the next two weeks

Good afternoon, is there any progress on our issue?

**Comment by swingerman** [comment]
> > I will have some time in the next two weeks
> 
> Good afternoon, is there any progress on our issue?

Hang on there. I had a rough month. Next week seems to be when I will have time

**Comment by swingerman** [comment]
See **v0.1.6-beta.1**

**Comment by djdfynec** [comment]
> See **v0.1.6-beta.1**

Everything seems fine, thank you
