### ISSUE TITLE
Add a fit option so entities with ranges other than 0-100 can be used 

### ISSUE THREAD

**Issue by zebraelch** [swingerman/lovelace-fluid-level-background-card#206]
Hi, thank you so much for this cool add-on, it really makes tank level displays a billion times cooler..

So I have a few tank level entities that don't work in percent, it would be great if you could add an option so I can set the entities lower and upper bounds. It can be done with a new sensor but would be more elegant in the actual add-on 😉

Thank you for your work, I feel this add-on is way under -appreciated by the HA community..

**Comment by Torrax** [comment]
Would defiantly love to see this as well so it can be used for water height and other liquids.

**Comment by Ftown14** [comment]
One of the forks did this, it could be pulled.

**Comment by swingerman** [comment]
What if we add an option where you can set the maximum value?

**Comment by swingerman** [comment]
please check [v0.1.6-beta.3](https://github.com/swingerman/lovelace-fluid-level-background-card/releases/tag/v0.1.6-beta.3)
