### ISSUE TITLE
Can not install in HACS

### ISSUE THREAD

**Issue by reketekui** [swingerman/lovelace-fluid-level-background-card#221]
Hello, when i try to add repository  HACS says:

Repository 'swingerman/lovelace-fluid-level-background-card' exists in the store.

But i can't find the fluid level background card. Thanks.

**Comment by swingerman** [comment]
I can see it in HACS:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/7681395/229217086-81752f57-efc7-472f-91da-7d681bc4026d.png">

Probably it's already installed. In this case, it won't show in the list of store items.
