### ISSUE TITLE
The card its not working 

### ISSUE THREAD

**Issue by homeyjoenka** [swingerman/lovelace-fluid-level-background-card#245]
The card is not working we have a failt
![045FDF43-1E27-4C35-89E0-57A3C35FA9A7](https://user-images.githubusercontent.com/61145850/229069641-0c0a5031-261c-4831-a1d7-451cd65bbb0d.png)

**Comment by swingerman** [comment]
I deleted the failed v1.3 release. Please re-download v1.2

**Comment by Homeassistjoenka** [comment]
Thank you yes its work now here

**Comment by Homeassistjoenka** [comment]
Your new release is working perfect Thank you
