### ISSUE TITLE
The card it,s not working with beta 2

### ISSUE THREAD

**Issue by Homeassistjoenka** [swingerman/lovelace-fluid-level-background-card#246]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Homeassistjoenka** [comment]
![image](https://user-images.githubusercontent.com/113582714/229072544-401998bf-f4ff-42ae-b448-1e3f015e1cc1.png)

**Comment by kulmegil** [comment]
This is related to #221 as release doesn't come with build, and HACS doesn't do that.

I can confirm both 1.2 and 1.3 (own build) works with beta (2023.4.0b2)

**Comment by Homeassistjoenka** [comment]
i not understandt, what we doe now?

**Comment by swingerman** [comment]
I deleted the failed release. Please re-download v1.2
