### ISSUE TITLE
Support for timers

### ISSUE THREAD

**Issue by laptopology** [swingerman/lovelace-fluid-level-background-card#251]
Is it possible to use a timer entity as a level entity?

**Comment by ildar170975** [comment]
The card is supposed to show a LEVEL which could be 0-100.
How this could be related to a timer?
A timer could be set to 15 sec, to 2 hours.
If you need to reflect a current progress - try to create a template sensor based on a timer's remaining value.

**Comment by swingerman** [comment]
I agree with @ildar170975 . Create a template sensor that transforms the timer output to apercentage.
