### ISSUE TITLE
Errors are flooding the Log (probably in case of wrong user's code)

### ISSUE THREAD

**Issue by ildar170975** [swingerman/lovelace-fluid-level-background-card#383]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
v0.1.6-beta.0

**Last working release (if known):**

**Browser and Operating System:**
Chrome 123.0.6312.59 (win10x64)

**Description of problem:**

Noticed that the Log is flooded by these errors:

-------------

2024-03-21 16:11:25.908 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-25) is negative.
v (/hacsfiles/lovelace-fluid-level-background-card/fluid-level-background-card.js:181:1290)
2024-03-21 16:11:25.909 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-25) is negative.
v (/hacsfiles/lovelace-fluid-level-background-card/fluid-level-background-card.js:181:1290)
2024-03-21 16:11:25.909 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-25) is negative.
v (/hacsfiles/lovelace-fluid-level-background-card/fluid-level-background-card.js:181:1290)
2024-03-21 16:11:25.910 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-25) is negative.
v (/hacsfiles/lovelace-fluid-level-background-card/fluid-level-background-card.js:181:1290)
2024-03-21 16:11:25.910 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-25) is negative.
v (/hacsfiles/lovelace-fluid-level-background-card/fluid-level-background-card.js:181:1290)
2024-03-21 16:11:25.911 ERROR (MainThread) [frontend.js.latest.202403070] Uncaught error from Chrome 123.0.0.0 on Windows 10
IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-25) is negative.
v (/hacsfiles/lovelace-fluid-level-background-card/fluid-level-background-card.js:181:1290)

---------------

Here is only a tiny amount of same messages. They are raised in a large amount within a small time interval.
Probably these errors are caused by a wrong user's code in the card config (I played with differently defined `level_color`).
Suggest to avoid this extensive generation of errors; some messages are surely should be reported - but not with this high frequency.

**Javascript errors shown in the web inspector (if applicable):**
I did not notice errors in console.
May be there were in fact.

**Additional information:**

**Comment by swingerman** [comment]
The errors you shared seem to indicate something not related to the level_color.

Could you share a screenshot of your card in Lovelace when this happens?

**Comment by ildar170975** [comment]
I tried to reproduce the case.
Here is a code:
```
type: custom:fluid-level-background-card
card:
  type: glance
  entities:
    - entity: sun.sun
      name: Beer level
entity: input_number.test_level_1
fill_entity: input_boolean.test_boolean
level_color:
  - 242
  - 142
  - 28
```
![изображение](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/8bafa623-fb1a-467a-91f5-a1cee746e30c)

What I did:
1. Edit a value of `level_color` - remove a list, start typing smth like 
```
level_color: [
```
adding smth in this line, removing etc.
2. And once I reproduced these errors - but have not noticed which exact change caused it, just saw same errors in the Log.
3. But I failed to reproduce it again.

**Comment by swingerman** [comment]
I see. While you are typing in the YAML editor, The card gets updated on each keystroke, resulting in invalid values that break the code.

**Comment by ildar170975** [comment]
Probably, and as I said I could not reproduce it, a bit erratic glitch...
Actually, a lot of cards report errors while typing an incomplete code, I would consider this as a normal behaviour.
The issue is about a high frequency.

**Comment by swingerman** [comment]
please check [v0.1.6-beta.2](https://github.com/swingerman/lovelace-fluid-level-background-card/releases/tag/v0.1.6-beta.2)

**Comment by ildar170975** [comment]
Started testing, see no errors so far.
Will report if I see them.
Thanks a lot!!!
