### ISSUE TITLE
Javascript errors shown in the web inspector - Faild to execute 'arc'

### ISSUE THREAD

**Issue by S1M8N** [swingerman/lovelace-fluid-level-background-card#400]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
-
Fluid level background card: v0.1.5
HA: 2024.4.3

**Last working release (if known):**
-
nothing

**Browser and Operating System:**
-
Opera GX and Windows 11

**Description of problem:**
-
I noticed that your integration was generating a lot of errors in the java script console. This slows me down during certain modifications.

EDIT : I've just seen that this problem has already been mentioned and is corrected in the beta version. I'll leave you to deal with this issue as you see fit.

**Javascript errors shown in the web inspector (if applicable):**
-

![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/75216525/c61631cd-301f-4879-a0ab-dff4170c9b89)

**Comment by swingerman** [comment]
duplicate #383 

This issue is fixed in the latest beta release
