### ISSUE TITLE
Full_value property

### ISSUE THREAD

**Issue by Apvilchez** [swingerman/lovelace-fluid-level-background-card#401]
Hello, I have implemented your card in my farm but instead of a percentage I try to control the value in liters of a tank, when I enter the property full_value: 1000 it has no effect, and with 80l, the water comes out practically full on the card. This is my configuration:

type: custom:fluid-level-background-card
card:
  full_value: 1000
  show_name: true
  show_icon: true
  type: button
  tap_action:
    action: none
  show_state: true
  entity: sensor.litros
  icon: mdi:barrel-outline
  hold_action:
    action: none
  name: Litros
level_color:
  - 33
  - 150
  - 243
entity: sensor.litros

I have tried to put full_value in different places but it still has no effect. I hope your help

**Comment by ildar170975** [comment]
@Apvilchez 
The code you posted is unformatted and cannot be properly analysed / reproduced.
Look at other issues & compare with yours.

**Comment by swingerman** [comment]
Are you using the latest beta?
