### ISSUE TITLE
Version in browser's console do not conform to expected

### ISSUE THREAD

**Issue by ildar170975** [swingerman/lovelace-fluid-level-background-card#408]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
0.1.6-beta.6

**Last working release (if known):**
?

**Browser and Operating System:**
Chrome 124.0.6367.119 
Win10x64

**Description of problem:**

Installed the latest v0.1.6-beta.6 - but cannot be 100% sure since the corr. data seems to be not properly shown:

![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/c43f4517-aae3-44b2-8942-f6b4dc33ff9f)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by ildar170975** [comment]
Was it added in 0.1.6?
Still see in js file:
![изображение](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/a67820f3-15f4-4903-bf3d-5fb7d8448fdb)

The js file is on a system where the card was previously deleted & then installed again.
Installed by HACS, version "0.1.6" was selected for installation.

**Comment by swingerman** [comment]
Sorry about that. I just cut a new release that will fix it.

**Comment by ildar170975** [comment]
Great, see it correct:
![изображение](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/e70b1800-9c07-4c5f-8e0b-715b8c1c2c2c)
Thanks a lot!
