### ISSUE TITLE
Display issue in older browser

### ISSUE THREAD

**Issue by warmbadger** [swingerman/lovelace-fluid-level-background-card#497]
**Checklist:**

- [ X] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
Core 2024.12.2 Supervisor 2024.11.4 Operating System 14.0
**Last working release (if known):**

**Browser and Operating System:**
Mac Safari and Chrome has no issues

  Amazon Fire 10 Tablet - firmware 1.55.1  - Fully Browser Kiosk Android version 9 FireOS

**Description of problem:**

 Doesn't display the card - here's a screenshot

![fully-screenshot](https://github.com/user-attachments/assets/61e276a8-cc79-40b0-8114-f73cba4a1ba5)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Nice cards, thanks for your efforts

**Comment by swingerman** [comment]
It seems that in that browser the canvas is not supported. This card needs that. Your omly options would be using a modern browser or installkng the official companion app on that tablet.

**Comment by warmbadger** [comment]
That's unfortunate, I was hoping it was as simple as whatever it was piitaya did here to support older browsers.

https://github.com/piitaya/lovelace-mushroom/pull/1585
